# This is an example local configuration, which defines settings for one
# individual's specific deployments of the CloudFormation template.

[upload]
bucket = "importbounce-lambda-XXXXXX"

[[stacks]]
name = "ImportBounceTest"
parameters = { DomainName = "go-test.alexhamlin.co" }

[[stacks]]
name = "ImportBouncePersonal"
parameters = { DomainName = "go.alexhamlin.co" }
