# This is an example project-level configuration, which defines settings that
# apply to all deployments of the CloudFormation template.

[project]
name = "randomizer"

# A region is useful in the global config for stacks whose resources can only
# exist there, e.g. TLS certificates for CloudFront must be in us-east-1.
# Otherwise, hfc defaults to standard AWS SDK behavior.
#
# [aws]
# region = "us-east-1"

[build]
path = "./cmd/randomizer"
tags = ["grpcnotrace"]

[template]
path = "CloudFormation.yaml"
capabilities = ["CAPABILITY_IAM"]
