# This is an example local configuration, which defines settings for one
# individual's deployments of the CloudFormation template.

[upload]
bucket = "randomizer-lambda-XXXXXX"

[[stacks]]
name = "RandomizerStaging"
parameters = { SlackTokenSSMName = "RandomizerStaging/SlackToken" }

[[stacks]]
name = "RandomizerProduction"
parameters = { SlackTokenSSMName = "RandomizerProduction/SlackToken" }
